# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JSFighters
email: gyula.nemeth@edmdesigner.com
description: > # this means to ignore newlines until "baseurl:"
  JSFighters is a place where you improve yourself by helping others with their open source projects.
  /
  JSFighters is a place where you mentor others by giving them challenging quests in your open source projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jsfighters.edmdesigner.com" # the base hostname & protocol for your site
github_username:  edmdesigner

pages: about members

# Build settings
markdown: kramdown

future: false
